import { permissionGuard } from '@abp/ng.core';
import { NgModule } from '@angular/core';
import { Route, RouterModule, Routes } from '@angular/router';
import { SalesInvoicesComponent } from './pages/sales-invoices/sales-invoices.component';
import { PurchaseInvoicesComponent } from './pages/purchase-invoices/purchase-invoices.component';
import { moduleGuard } from './services/module.guard';

function masterData(path: string, entity: string, requiredPolicy: string, module: string): Route {
  return {
    path,
    loadChildren: () => import('./master-data/master-data.module').then(m => m.MasterDataModule),
    canActivate: [permissionGuard, moduleGuard],
    // Component-less, so the list and card pages below inherit `entity`.
    data: { entity, requiredPolicy, module },
  };
}

const routes: Routes = [
  // The role centre is the application's landing page now, so /erp has nothing of its own.
  { path: '', redirectTo: '/', pathMatch: 'full' },
  { path: 'dashboard', redirectTo: '/', pathMatch: 'full' },
  // Master data: one lazy module serves the list and card pages of every table, see `MasterDataEntities`.
  masterData('chart-of-accounts', 'glAccount', 'Erp.GLAccounts', 'Finance'),
  masterData('customers', 'customer', 'Erp.Customers', 'Sales'),
  masterData('vendors', 'vendor', 'Erp.Vendors', 'Purchasing'),
  masterData('items', 'item', 'Erp.Items', 'Inventory'),
  masterData('units-of-measure', 'unitOfMeasure', 'Erp.UnitsOfMeasure', 'Inventory'),
  masterData('item-categories', 'itemCategory', 'Erp.ItemCategories', 'Inventory'),
  // Posting groups and the setups that turn them into G/L accounts.
  masterData('gen-bus-posting-groups', 'genBusPostingGroup', 'Erp.PostingSetup', 'Finance'),
  masterData('gen-prod-posting-groups', 'genProdPostingGroup', 'Erp.PostingSetup', 'Finance'),
  masterData('customer-posting-groups', 'customerPostingGroup', 'Erp.PostingSetup', 'Sales'),
  masterData('vendor-posting-groups', 'vendorPostingGroup', 'Erp.PostingSetup', 'Purchasing'),
  masterData('inventory-posting-groups', 'inventoryPostingGroup', 'Erp.PostingSetup', 'Inventory'),
  masterData('general-posting-setup', 'generalPostingSetup', 'Erp.PostingSetup', 'Finance'),
  masterData('inventory-posting-setup', 'inventoryPostingSetup', 'Erp.PostingSetup', 'Inventory'),
  // Tax, finance, cash management, inventory, sales and human resources setup.
  masterData('vat-bus-posting-groups', 'vatBusPostingGroup', 'Erp.PostingSetup', 'Finance'),
  masterData('vat-prod-posting-groups', 'vatProdPostingGroup', 'Erp.PostingSetup', 'Finance'),
  masterData('vat-posting-setup', 'vatPostingSetup', 'Erp.PostingSetup', 'Finance'),
  masterData('payment-terms', 'paymentTerms', 'Erp.FinanceSetup', 'Finance'),
  masterData('currencies', 'currency', 'Erp.FinanceSetup', 'Finance'),
  masterData('currency-exchange-rates', 'currencyExchangeRate', 'Erp.FinanceSetup', 'Finance'),
  masterData('payment-methods', 'paymentMethod', 'Erp.FinanceSetup', 'Finance'),
  masterData('bank-account-posting-groups', 'bankAccountPostingGroup', 'Erp.PostingSetup', 'CashManagement'),
  masterData('bank-accounts', 'bankAccount', 'Erp.BankAccounts', 'CashManagement'),
  masterData('locations', 'location', 'Erp.Locations', 'Inventory'),
  masterData('salespeople-purchasers', 'salespersonPurchaser', 'Erp.SalespeoplePurchasers', 'Sales'),
  masterData('employees', 'employee', 'Erp.Employees', 'HumanResources'),
  masterData('employee-absences', 'employeeAbsence', 'Erp.Employees', 'HumanResources'),
  masterData('causes-of-absence', 'causeOfAbsence', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('qualifications', 'qualification', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('unions', 'union', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('employment-contracts', 'employmentContract', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('grounds-for-termination', 'groundsForTermination', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('hr-units-of-measure', 'hrUnitOfMeasure', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('employee-posting-groups', 'employeePostingGroup', 'Erp.HumanResourcesSetup', 'HumanResources'),
  // Base tables: setup, fixed assets, budgets, bank reconciliation and read-only sub-ledgers.
  masterData('source-codes', 'sourceCode', 'Erp.FinanceSetup', 'Finance'),
  masterData('reason-codes', 'reasonCode', 'Erp.FinanceSetup', 'Finance'),
  masterData('countries-regions', 'countryRegion', 'Erp.FinanceSetup', 'Finance'),
  masterData('post-codes', 'postCode', 'Erp.FinanceSetup', 'Finance'),
  masterData('shipment-methods', 'shipmentMethod', 'Erp.FinanceSetup', 'Finance'),
  masterData('responsibility-centers', 'responsibilityCenter', 'Erp.FinanceSetup', 'Finance'),
  masterData('user-setups', 'userSetup', 'Erp.UserSetup', 'Finance'),
  masterData('gl-budget-names', 'glBudgetName', 'Erp.Budgets', 'Finance'),
  masterData('gl-budget-entries', 'glBudgetEntry', 'Erp.Budgets', 'Finance'),
  masterData('comment-lines', 'commentLine', 'Erp.Comments', 'Finance'),
  masterData('customer-bank-accounts', 'customerBankAccount', 'Erp.Customers', 'Sales'),
  masterData('detailed-cust-ledg-entries', 'detailedCustLedgEntry', 'Erp.Customers', 'Sales'),
  masterData('vendor-bank-accounts', 'vendorBankAccount', 'Erp.Vendors', 'Purchasing'),
  masterData('detailed-vendor-ledg-entries', 'detailedVendorLedgEntry', 'Erp.Vendors', 'Purchasing'),
  masterData('order-addresses', 'orderAddress', 'Erp.Vendors', 'Purchasing'),
  masterData('item-vendors', 'itemVendor', 'Erp.Vendors', 'Purchasing'),
  masterData('purch-comment-lines', 'purchCommentLine', 'Erp.PurchaseDocuments', 'Purchasing'),
  masterData('bank-acc-reconciliations', 'bankAccReconciliation', 'Erp.BankReconciliations', 'CashManagement'),
  masterData('bank-acc-reconciliation-lines', 'bankAccReconciliationLine', 'Erp.BankReconciliations', 'CashManagement'),
  masterData('bank-account-statements', 'bankAccountStatement', 'Erp.BankReconciliations', 'CashManagement'),
  masterData('bank-account-statement-lines', 'bankAccountStatementLine', 'Erp.BankReconciliations', 'CashManagement'),
  masterData('check-ledger-entries', 'checkLedgerEntry', 'Erp.BankAccounts', 'CashManagement'),
  masterData('relatives', 'relative', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('misc-articles', 'miscArticle', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('confidentials', 'confidential', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('employee-statistics-groups', 'employeeStatisticsGroup', 'Erp.HumanResourcesSetup', 'HumanResources'),
  masterData('employee-relatives', 'employeeRelative', 'Erp.Employees', 'HumanResources'),
  masterData('employee-qualifications', 'employeeQualification', 'Erp.Employees', 'HumanResources'),
  masterData('misc-article-informations', 'miscArticleInformation', 'Erp.Employees', 'HumanResources'),
  masterData('confidential-informations', 'confidentialInformation', 'Erp.Employees', 'HumanResources'),
  masterData('alternative-addresses', 'alternativeAddress', 'Erp.Employees', 'HumanResources'),
  masterData('human-resource-comment-lines', 'humanResourceCommentLine', 'Erp.Employees', 'HumanResources'),
  masterData('fa-classes', 'faClass', 'Erp.FixedAssetSetup', 'FixedAssets'),
  masterData('fa-subclasses', 'faSubclass', 'Erp.FixedAssetSetup', 'FixedAssets'),
  masterData('fa-locations', 'faLocation', 'Erp.FixedAssetSetup', 'FixedAssets'),
  masterData('maintenances', 'maintenance', 'Erp.FixedAssetSetup', 'FixedAssets'),
  masterData('depreciation-books', 'depreciationBook', 'Erp.FixedAssetSetup', 'FixedAssets'),
  masterData('fa-posting-groups', 'faPostingGroup', 'Erp.FixedAssetSetup', 'FixedAssets'),
  masterData('fixed-assets', 'fixedAsset', 'Erp.FixedAssets', 'FixedAssets'),
  masterData('fa-depreciation-books', 'faDepreciationBook', 'Erp.FixedAssets', 'FixedAssets'),
  masterData('fa-ledger-entries', 'faLedgerEntry', 'Erp.FixedAssets', 'FixedAssets'),
  masterData('maintenance-registrations', 'maintenanceRegistration', 'Erp.FixedAssets', 'FixedAssets'),
  masterData('main-asset-components', 'mainAssetComponent', 'Erp.FixedAssets', 'FixedAssets'),
  masterData('report-selections', 'reportSelection', 'Erp.ReportSelections', 'Reporting'),
  masterData('custom-report-selections', 'customReportSelection', 'Erp.ReportSelections', 'Reporting'),
  masterData('workflow-user-groups', 'workflowUserGroup', 'Erp.WorkflowUserGroups', 'Approvals'),
  masterData('workflow-user-group-members', 'workflowUserGroupMember', 'Erp.WorkflowUserGroups', 'Approvals'),
  masterData('approval-comment-lines', 'approvalCommentLine', 'Erp.ApprovalComments', 'Approvals'),
  // Pensions: schemes are values of a dimension, so every scheme of the administrator lives in this company.
  masterData('pension-schemes', 'pensionScheme', 'Erp.PensionSetup', 'Pensions'),
  masterData('pension-sponsors', 'pensionSponsor', 'Erp.Pensions', 'Pensions'),
  masterData('pension-members', 'pensionMember', 'Erp.Pensions', 'Pensions'),
  masterData('pension-contributions', 'pensionContribution', 'Erp.Pensions', 'Pensions'),
  masterData('pension-contribution-lines', 'pensionContributionLine', 'Erp.Pensions', 'Pensions'),
  masterData('member-exits', 'memberExit', 'Erp.Pensions', 'Pensions'),
  masterData('member-ledger-entries', 'memberLedgerEntry', 'Erp.Pensions', 'Pensions'),
  masterData('pension-interest-rates', 'pensionInterestRate', 'Erp.PensionSetup', 'Pensions'),
  masterData('exit-reasons', 'exitReason', 'Erp.PensionSetup', 'Pensions'),
  masterData('lumpsum-tax-tables', 'lumpsumTaxTable', 'Erp.PensionSetup', 'Pensions'),
  masterData('lumpsum-tax-bands', 'lumpsumTaxBand', 'Erp.PensionSetup', 'Pensions'),
  // Academics: students are billed through customer accounts of their own number.
  masterData('student-applications', 'studentApplication', 'Erp.Academics', 'Academics'),
  masterData('students', 'student', 'Erp.Academics', 'Academics'),
  masterData('semester-registrations', 'semesterRegistration', 'Erp.Academics', 'Academics'),
  masterData('student-units', 'studentUnit', 'Erp.Academics', 'Academics'),
  masterData('student-bills', 'studentBill', 'Erp.Academics', 'Academics'),
  masterData('student-bill-lines', 'studentBillLine', 'Erp.Academics', 'Academics'),
  masterData('exam-results', 'examResult', 'Erp.Academics', 'Academics'),
  masterData('exam-result-lines', 'examResultLine', 'Erp.Academics', 'Academics'),
  masterData('programmes', 'programme', 'Erp.AcademicSetup', 'Academics'),
  masterData('programme-stages', 'programmeStage', 'Erp.AcademicSetup', 'Academics'),
  masterData('course-units', 'courseUnit', 'Erp.AcademicSetup', 'Academics'),
  masterData('academic-years', 'academicYear', 'Erp.AcademicSetup', 'Academics'),
  masterData('semesters', 'semester', 'Erp.AcademicSetup', 'Academics'),
  masterData('intakes', 'intake', 'Erp.AcademicSetup', 'Academics'),
  masterData('exam-categories', 'examCategory', 'Erp.AcademicSetup', 'Academics'),
  masterData('grading-bands', 'gradingBand', 'Erp.AcademicSetup', 'Academics'),
  masterData('exam-components', 'examComponent', 'Erp.AcademicSetup', 'Academics'),
  masterData('fee-items', 'feeItem', 'Erp.AcademicSetup', 'Academics'),
  masterData('fee-structure', 'feeStructureLine', 'Erp.AcademicSetup', 'Academics'),
  masterData('student-receipts', 'studentReceipt', 'Erp.Academics', 'Academics'),
  masterData('student-refunds', 'studentRefund', 'Erp.Academics', 'Academics'),
  masterData('student-status-changes', 'studentStatusChange', 'Erp.Academics', 'Academics'),
  masterData('pensioners', 'pensioner', 'Erp.Pensions', 'Pensions'),
  masterData('pension-payrolls', 'pensionPayroll', 'Erp.Pensions', 'Pensions'),
  masterData('pension-payroll-lines', 'pensionPayrollLine', 'Erp.Pensions', 'Pensions'),
  masterData('pension-benefit-calculations', 'pensionBenefitCalculation', 'Erp.Pensions', 'Pensions'),
  masterData('pension-beneficiaries', 'pensionBeneficiary', 'Erp.Pensions', 'Pensions'),
  masterData('pension-contribution-rates', 'pensionContributionRate', 'Erp.Pensions', 'Pensions'),
  masterData('pension-vesting-scales', 'pensionVestingScale', 'Erp.Pensions', 'Pensions'),
  masterData('pension-tax-relief-limits', 'pensionTaxReliefLimit', 'Erp.PensionSetup', 'Pensions'),
  masterData('member-status-entries', 'memberStatusEntry', 'Erp.Pensions', 'Pensions'),
  masterData('member-salary-entries', 'memberSalaryEntry', 'Erp.Pensions', 'Pensions'),
  masterData('pension-increments', 'pensionIncrement', 'Erp.Pensions', 'Pensions'),
  masterData('pensioner-change-entries', 'pensionerChangeEntry', 'Erp.Pensions', 'Pensions'),
  masterData('pension-banks', 'pensionBank', 'Erp.PensionSetup', 'Pensions'),
  masterData('pension-bank-branches', 'pensionBankBranch', 'Erp.PensionSetup', 'Pensions'),
  masterData('pensioner-pay-modes', 'pensionerPayMode', 'Erp.PensionSetup', 'Pensions'),
  masterData('pensioner-pay-items', 'pensionerPayItem', 'Erp.PensionSetup', 'Pensions'),
  masterData('pensioner-suspension-reasons', 'pensionerSuspensionReason', 'Erp.PensionSetup', 'Pensions'),
  masterData('pension-revision-reasons', 'pensionRevisionReason', 'Erp.PensionSetup', 'Pensions'),
  masterData('other-pension-schemes', 'otherPensionScheme', 'Erp.PensionSetup', 'Pensions'),
  masterData('exit-reason-documents', 'exitReasonDocument', 'Erp.PensionSetup', 'Pensions'),
  masterData('pension-age-factors', 'pensionAgeFactor', 'Erp.PensionSetup', 'Pensions'),
  masterData('pensioner-pay-item-assignments', 'pensionerPayItemAssignment', 'Erp.Pensions', 'Pensions'),
  masterData('pension-payroll-line-items', 'pensionPayrollLineItem', 'Erp.Pensions', 'Pensions'),
  masterData('member-exit-documents', 'memberExitDocument', 'Erp.Pensions', 'Pensions'),
  // Campus services: timetable, attendance, hostels, infirmary, laundry and short courses.
  masterData('lecture-rooms', 'lectureRoom', 'Erp.AcademicSetup', 'Academics'),
  masterData('timetable', 'timetableEntry', 'Erp.Academics', 'Academics'),
  masterData('attendance-registers', 'attendanceRegister', 'Erp.Academics', 'Academics'),
  masterData('attendance-lines', 'attendanceLine', 'Erp.Academics', 'Academics'),
  masterData('hostels', 'hostel', 'Erp.AcademicSetup', 'Academics'),
  masterData('hostel-rooms', 'hostelRoom', 'Erp.AcademicSetup', 'Academics'),
  masterData('hostel-allocations', 'hostelAllocation', 'Erp.Academics', 'Academics'),
  masterData('clinic-visits', 'clinicVisit', 'Erp.Academics', 'Academics'),
  masterData('clinic-prescriptions', 'clinicPrescription', 'Erp.Academics', 'Academics'),
  masterData('laundry-items', 'laundryItem', 'Erp.AcademicSetup', 'Academics'),
  masterData('laundry-orders', 'laundryOrder', 'Erp.Academics', 'Academics'),
  masterData('laundry-order-lines', 'laundryOrderLine', 'Erp.Academics', 'Academics'),
  masterData('short-courses', 'shortCourse', 'Erp.AcademicSetup', 'Academics'),
  masterData('short-course-applications', 'shortCourseApplication', 'Erp.Academics', 'Academics'),
  masterData('short-course-participants', 'shortCourseParticipant', 'Erp.Academics', 'Academics'),
  // Payroll: net pay is credited to each employee's account and paid through a payment voucher.
  masterData('payroll-earnings', 'payrollEarning', 'Erp.PayrollSetup', 'Payroll'),
  masterData('payroll-deductions', 'payrollDeduction', 'Erp.PayrollSetup', 'Payroll'),
  masterData('payroll-tax-bands', 'payrollTaxBand', 'Erp.PayrollSetup', 'Payroll'),
  masterData('employee-pay-items', 'employeePayItem', 'Erp.Payroll', 'Payroll'),
  masterData('payroll-runs', 'payrollRun', 'Erp.Payroll', 'Payroll'),
  masterData('payslips', 'payslip', 'Erp.Payroll', 'Payroll'),
  masterData('payslip-lines', 'payslipLine', 'Erp.Payroll', 'Payroll'),
  // Payment vouchers: also what fee refunds, exit benefits and pension payrolls are paid through.
  masterData('payment-vouchers', 'paymentVoucher', 'Erp.PaymentVouchers', 'CashManagement'),
  masterData('payment-voucher-lines', 'paymentVoucherLine', 'Erp.PaymentVouchers', 'CashManagement'),
  masterData('payment-types', 'paymentType', 'Erp.PaymentVoucherSetup', 'CashManagement'),
  masterData('payment-deduction-codes', 'paymentDeductionCode', 'Erp.PaymentVoucherSetup', 'CashManagement'),
  {
    path: 'sales-invoices',
    component: SalesInvoicesComponent,
    canActivate: [permissionGuard, moduleGuard],
    data: { requiredPolicy: 'Erp.SalesDocuments', module: 'Sales' },
  },
  {
    path: 'purchase-invoices',
    component: PurchaseInvoicesComponent,
    canActivate: [permissionGuard, moduleGuard],
    data: { requiredPolicy: 'Erp.PurchaseDocuments', module: 'Purchasing' },
  },
  // The old single-report page has been replaced by the report viewer under /reports.
  { path: 'financial-reports', redirectTo: 'reports/financial', pathMatch: 'full' },
  {
    path: 'approvals',
    loadChildren: () => import('./approvals/approvals.module').then(m => m.ApprovalsModule),
    canActivate: [permissionGuard, moduleGuard],
    data: { requiredPolicy: 'Erp.Workflows', module: 'Approvals' },
  },
  {
    path: 'finance',
    loadChildren: () => import('./finance/finance.module').then(m => m.FinanceModule),
  },
  {
    path: 'reports',
    loadChildren: () => import('./reports/reports.module').then(m => m.ReportsModule),
    canActivate: [moduleGuard],
    data: { module: 'Reporting' },
  },
  { path: 'setup', loadChildren: () => import('./setup/setup.module').then(m => m.SetupModule) },
  {
    path: 'rapid-start',
    loadChildren: () => import('./rapid-start/rapid-start.module').then(m => m.RapidStartModule),
    canActivate: [moduleGuard],
    // Unknown to the module list until the backend registers it, which the guard treats as on.
    data: { module: 'RapidStart' },
  },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class ErpRoutingModule {}
