import { ABP, RoutesService, eLayoutType } from '@abp/ng.core';
import { NavItemsService } from '@abp/ng.theme.shared';
import { APP_INITIALIZER, inject, provideAppInitializer } from '@angular/core';
import { CompanyMenuComponent } from './erp/components/company-menu/company-menu.component';
import { MenuSuiteButtonComponent } from './erp/components/menu-suite/menu-suite-button.component';
import { PageSearchComponent } from './erp/components/menu-suite/page-search.component';

/**
 * The module each ERP menu entry belongs to. Entries of a module this company has switched off are
 * left out of the menu; see `ErpModuleRoutesService`. Anything not named here belongs to the core
 * and is always shown.
 */
export const ERP_ROUTE_MODULE: Record<string, string> = {
  'Erp::Menu:ChartOfAccounts': 'Finance',
  'Erp::Menu:Journals': 'Finance',
  'Erp::Menu:SalesInvoices': 'Sales',
  'Erp::Menu:PurchaseInvoices': 'Purchasing',
  'Erp::Menu:Reports': 'Reporting',
  'Erp::Menu:RequestsToApprove': 'Approvals',
  'Erp::Menu:Workflows': 'Approvals',
  'Erp::Menu:ApprovalUserSetup': 'Approvals',
  'Erp::Menu:WebServices': 'Integration',
  'Erp::Menu:Webhooks': 'Integration',
  'Erp::Menu:JobQueue': 'Core',
  'Erp::Menu:DataExport': 'DataExport',
  'Erp::Menu:Customers': 'Sales',
  'Erp::Menu:Vendors': 'Purchasing',
  'Erp::Menu:Items': 'Inventory',
  'Erp::Menu:UnitsOfMeasure': 'Inventory',
  'Erp::Menu:ItemCategories': 'Inventory',
  'Erp::Menu:GeneralLedgerSetup': 'Finance',
  'Erp::Menu:GenBusPostingGroups': 'Finance',
  'Erp::Menu:GenProdPostingGroups': 'Finance',
  'Erp::Menu:GeneralPostingSetup': 'Finance',
  'Erp::Menu:CustomerPostingGroups': 'Sales',
  'Erp::Menu:VendorPostingGroups': 'Purchasing',
  'Erp::Menu:InventoryPostingGroups': 'Inventory',
  'Erp::Menu:InventoryPostingSetup': 'Inventory',
  'Erp::Menu:VatBusPostingGroups': 'Finance',
  'Erp::Menu:VatProdPostingGroups': 'Finance',
  'Erp::Menu:VatPostingSetup': 'Finance',
  'Erp::Menu:PaymentTerms': 'Finance',
  'Erp::Menu:Currencies': 'Finance',
  'Erp::Menu:CurrencyExchangeRates': 'Finance',
  'Erp::Menu:AccountingPeriods': 'Finance',
  'Erp::Menu:VatEntries': 'Finance',
  'Erp::Menu:PaymentMethods': 'Finance',
  'Erp::Menu:CashManagement': 'CashManagement',
  'Erp::Menu:BankAccounts': 'CashManagement',
  'Erp::Menu:BankAccountLedgerEntries': 'CashManagement',
  'Erp::Menu:BankAccountPostingGroups': 'CashManagement',
  'Erp::Menu:Locations': 'Inventory',
  'Erp::Menu:InventorySetup': 'Inventory',
  'Erp::Menu:SalespeoplePurchasers': 'Sales',
  'Erp::Menu:HumanResources': 'HumanResources',
  'Erp::Menu:Employees': 'HumanResources',
  'Erp::Menu:EmployeeAbsences': 'HumanResources',
  'Erp::Menu:CausesOfAbsence': 'HumanResources',
  'Erp::Menu:Qualifications': 'HumanResources',
  'Erp::Menu:Unions': 'HumanResources',
  'Erp::Menu:EmploymentContracts': 'HumanResources',
  'Erp::Menu:PeriodicActivities': 'Finance',
  'Erp::Menu:VatStatement': 'Finance',
  'Erp::Menu:VatSettlement': 'Finance',
  'Erp::Menu:AdjustExchangeRates': 'Finance',
  'Erp::Menu:CustomerLedgerEntries': 'Sales',
  'Erp::Menu:VendorLedgerEntries': 'Purchasing',
  'Erp::Menu:EmployeeLedgerEntries': 'HumanResources',
  'Erp::Menu:GroundsForTermination': 'HumanResources',
  'Erp::Menu:HumanResourceUnitsOfMeasure': 'HumanResources',
  'Erp::Menu:EmployeePostingGroups': 'HumanResources',
  'Erp::Menu:HumanResourcesSetup': 'HumanResources',
  'Erp::Menu:ConfigWorksheet': 'RapidStart',
  'Erp::Menu:ConfigPackages': 'RapidStart',
  'Erp::Menu:ConfigTemplates': 'RapidStart',
  'Erp::Menu:ImportData': 'RapidStart',
};

/** The ERP menu, defined once so it can be rebuilt when a module is switched on or off. */
export const ERP_ROUTES: ABP.Route[] = [
  {
    path: '/',
    name: 'Erp::Menu:Home',
    iconClass: 'fas fa-home',
    order: 1,
    layout: eLayoutType.application,
  },
  {
    path: '/erp',
    name: 'Erp::Menu:Erp',
    iconClass: 'fas fa-calculator',
    order: 2,
    layout: eLayoutType.application,
  },
  {
    path: '/erp/chart-of-accounts',
    name: 'Erp::Menu:ChartOfAccounts',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-list-ol',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.GLAccounts',
  },
  {
    path: '/erp/sales-invoices',
    name: 'Erp::Menu:SalesInvoices',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-file-invoice-dollar',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.SalesDocuments',
  },
  {
    path: '/erp/purchase-invoices',
    name: 'Erp::Menu:PurchaseInvoices',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-shopping-cart',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PurchaseDocuments',
  },
  {
    // A group only: the tables every document and journal line looks records up in.
    name: 'Erp::Menu:MasterData',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-database',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy:
      'Erp.Customers || Erp.Vendors || Erp.Items || Erp.UnitsOfMeasure || Erp.ItemCategories || Erp.Locations || Erp.SalespeoplePurchasers',
  },
  {
    path: '/erp/customers',
    name: 'Erp::Menu:Customers',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-user-tie',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Customers',
  },
  {
    path: '/erp/vendors',
    name: 'Erp::Menu:Vendors',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-truck-field',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Vendors',
  },
  {
    path: '/erp/finance/customer-ledger-entries',
    name: 'Erp::Menu:CustomerLedgerEntries',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-file-invoice',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Customers',
  },
  {
    path: '/erp/finance/vendor-ledger-entries',
    name: 'Erp::Menu:VendorLedgerEntries',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-file-invoice',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Vendors',
  },
  {
    path: '/erp/items',
    name: 'Erp::Menu:Items',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-box',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Items',
  },
  {
    path: '/erp/units-of-measure',
    name: 'Erp::Menu:UnitsOfMeasure',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-ruler-combined',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.UnitsOfMeasure',
  },
  {
    path: '/erp/item-categories',
    name: 'Erp::Menu:ItemCategories',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-sitemap',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ItemCategories',
  },
  {
    path: '/erp/locations',
    name: 'Erp::Menu:Locations',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-warehouse',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Locations',
  },
  {
    path: '/erp/salespeople-purchasers',
    name: 'Erp::Menu:SalespeoplePurchasers',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-user-tag',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.SalespeoplePurchasers',
  },
  {
    // A group only: the posting groups master data carries and the setups that turn them into
    // G/L accounts (BC's "Posting Groups" and "Posting Setup" pages).
    name: 'Erp::Menu:PostingSetup',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-diagram-project',
    order: 85,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/general-posting-setup',
    name: 'Erp::Menu:GeneralPostingSetup',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-table-cells',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/gen-bus-posting-groups',
    name: 'Erp::Menu:GenBusPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-people-group',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/gen-prod-posting-groups',
    name: 'Erp::Menu:GenProdPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-tags',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/customer-posting-groups',
    name: 'Erp::Menu:CustomerPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-user-tag',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vendor-posting-groups',
    name: 'Erp::Menu:VendorPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-truck-ramp-box',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/inventory-posting-groups',
    name: 'Erp::Menu:InventoryPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-warehouse',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/inventory-posting-setup',
    name: 'Erp::Menu:InventoryPostingSetup',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-boxes-stacked',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vat-posting-setup',
    name: 'Erp::Menu:VatPostingSetup',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-receipt',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vat-bus-posting-groups',
    name: 'Erp::Menu:VatBusPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-user-shield',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vat-prod-posting-groups',
    name: 'Erp::Menu:VatProdPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-percent',
    order: 10,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    // A group only: the finance code tables and the VAT ledger (BC's Finance setup pages).
    name: 'Erp::Menu:FinanceSetup',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-scale-balanced',
    order: 84,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup || Erp.VatEntries',
  },
  {
    path: '/erp/payment-terms',
    name: 'Erp::Menu:PaymentTerms',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-calendar-day',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/currencies',
    name: 'Erp::Menu:Currencies',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-money-bill-wave',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/currency-exchange-rates',
    name: 'Erp::Menu:CurrencyExchangeRates',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-right-left',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/finance/accounting-periods',
    name: 'Erp::Menu:AccountingPeriods',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-calendar-alt',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/payment-methods',
    name: 'Erp::Menu:PaymentMethods',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-credit-card',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/finance/vat-entries',
    name: 'Erp::Menu:VatEntries',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-receipt',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.VatEntries',
  },
  {
    // A group only: the period-end jobs (BC's "Periodic Activities" under Financial Management).
    name: 'Erp::Menu:PeriodicActivities',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-calendar-check',
    order: 85,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PeriodicActivities || Erp.VatEntries',
  },
  {
    path: '/erp/finance/vat-return',
    name: 'Erp::Menu:VatStatement',
    parentName: 'Erp::Menu:PeriodicActivities',
    iconClass: 'fas fa-file-invoice-dollar',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.VatEntries',
  },
  {
    path: '/erp/finance/vat-settlement',
    name: 'Erp::Menu:VatSettlement',
    parentName: 'Erp::Menu:PeriodicActivities',
    iconClass: 'fas fa-scale-balanced',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PeriodicActivities.SettleVat',
  },
  {
    path: '/erp/finance/exch-rate-adjustment',
    name: 'Erp::Menu:AdjustExchangeRates',
    parentName: 'Erp::Menu:PeriodicActivities',
    iconClass: 'fas fa-right-left',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PeriodicActivities',
  },
  {
    // A group only: bank accounts and their setup (BC's Cash Management).
    name: 'Erp::Menu:CashManagement',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-building-columns',
    order: 86,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankAccounts || Erp.PostingSetup',
  },
  {
    path: '/erp/bank-accounts',
    name: 'Erp::Menu:BankAccounts',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-building-columns',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankAccounts',
  },
  {
    path: '/erp/finance/bank-ledger-entries',
    name: 'Erp::Menu:BankAccountLedgerEntries',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-list-ul',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankAccounts',
  },
  {
    path: '/erp/bank-account-posting-groups',
    name: 'Erp::Menu:BankAccountPostingGroups',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-vault',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    // A group only: employees, absences and the HR code tables (BC's Human Resources).
    name: 'Erp::Menu:HumanResources',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-id-badge',
    order: 87,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees || Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employees',
    name: 'Erp::Menu:Employees',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-id-badge',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/finance/employee-ledger-entries',
    name: 'Erp::Menu:EmployeeLedgerEntries',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-receipt',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/employee-absences',
    name: 'Erp::Menu:EmployeeAbsences',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-umbrella-beach',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/causes-of-absence',
    name: 'Erp::Menu:CausesOfAbsence',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-notes-medical',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/qualifications',
    name: 'Erp::Menu:Qualifications',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-graduation-cap',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employment-contracts',
    name: 'Erp::Menu:EmploymentContracts',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-file-signature',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/unions',
    name: 'Erp::Menu:Unions',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-handshake',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/grounds-for-termination',
    name: 'Erp::Menu:GroundsForTermination',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-door-open',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/hr-units-of-measure',
    name: 'Erp::Menu:HumanResourceUnitsOfMeasure',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-hourglass-half',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employee-posting-groups',
    name: 'Erp::Menu:EmployeePostingGroups',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-people-arrows',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    // A group only: it has no page of its own.
    name: 'Erp::Menu:Journals',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-book',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Journals || Erp.GLRegisters',
  },
  {
    path: '/erp/finance/general-journal',
    name: 'Erp::Menu:GeneralJournal',
    parentName: 'Erp::Menu:Journals',
    iconClass: 'fas fa-pen-to-square',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Journals',
  },
  {
    path: '/erp/finance/journal-templates',
    name: 'Erp::Menu:JournalTemplates',
    parentName: 'Erp::Menu:Journals',
    iconClass: 'fas fa-layer-group',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Journals',
  },
  {
    path: '/erp/finance/registers',
    name: 'Erp::Menu:GLRegisters',
    parentName: 'Erp::Menu:Journals',
    iconClass: 'fas fa-clock-rotate-left',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.GLRegisters',
  },
  {
    name: 'Erp::Menu:Reports',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-chart-line',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Reports || Erp.AccountSchedules',
  },
  {
    path: '/erp/reports/financial',
    name: 'Erp::Menu:FinancialReports',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-file-invoice',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Reports',
  },
  {
    path: '/erp/reports/account-schedules',
    name: 'Erp::Menu:AccountSchedules',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-table',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.AccountSchedules',
  },
  {
    path: '/erp/reports/column-layouts',
    name: 'Erp::Menu:ColumnLayouts',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-table-columns',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.AccountSchedules',
  },
  {
    path: '/erp/reports/report-layouts',
    name: 'Erp::Menu:ReportLayouts',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-file-invoice',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ReportLayouts',
  },
  {
    path: '/erp/approvals',
    name: 'Erp::Menu:RequestsToApprove',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-clipboard-check',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Workflows',
  },
  {
    // A group only: it has no page of its own.
    name: 'Erp::Menu:Setup',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-cog',
    order: 90,
    layout: eLayoutType.application,
    requiredPolicy:
      'Erp.Modules || Erp.Theme || Erp.Profiles || Erp.GeneralLedgerSetup || Erp.InventorySetup || Erp.HumanResourcesSetup || Erp.NoSeries || Erp.SalesSetup || Erp.PurchaseSetup || Erp.Workflows || Erp.ApprovalUserSetup || Erp.WebServices || Erp.Webhooks || Erp.DataExport || Erp.RapidStart',
  },
  {
    path: '/erp/setup/modules',
    name: 'Erp::Menu:Modules',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-sliders',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Modules',
  },
  {
    path: '/erp/setup/theme',
    name: 'Erp::Menu:Theme',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-palette',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Theme',
  },
  {
    path: '/erp/setup/profiles',
    name: 'Erp::Menu:Profiles',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-users-gear',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Profiles',
  },
  {
    path: '/erp/setup/general-ledger',
    name: 'Erp::Menu:GeneralLedgerSetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-book',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.GeneralLedgerSetup',
  },
  {
    path: '/erp/setup/inventory',
    name: 'Erp::Menu:InventorySetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-boxes-stacked',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.InventorySetup',
  },
  {
    path: '/erp/setup/human-resources',
    name: 'Erp::Menu:HumanResourcesSetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-id-card',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/setup/no-series',
    name: 'Erp::Menu:NoSeries',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-list-ol',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.NoSeries',
  },
  {
    path: '/erp/setup/document-numbering',
    name: 'Erp::DocumentNumbering',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-hashtag',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.NoSeries && (Erp.SalesSetup || Erp.PurchaseSetup)',
  },
  {
    path: '/erp/setup/workflows',
    name: 'Erp::Menu:Workflows',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-project-diagram',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Workflows.Manage',
  },
  {
    path: '/erp/setup/approval-users',
    name: 'Erp::Menu:ApprovalUserSetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-user-check',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ApprovalUserSetup',
  },
  {
    path: '/erp/setup/web-services',
    name: 'Erp::Menu:WebServices',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-plug',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.WebServices && Erp.DataExport',
  },
  {
    path: '/erp/setup/webhooks',
    name: 'Erp::Menu:Webhooks',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-satellite-dish',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Webhooks && Erp.DataExport',
  },
  {
    path: '/erp/setup/data-export',
    name: 'Erp::Menu:DataExport',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-file-export',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.DataExport',
  },
  {
    path: '/erp/setup/job-queue',
    name: 'Erp::Menu:JobQueue',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-tasks',
    order: 8.5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.JobQueue',
  },
  {
    path: '/erp/rapid-start/worksheet',
    name: 'Erp::Menu:ConfigWorksheet',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-list-check',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart',
  },
  {
    path: '/erp/rapid-start/packages',
    name: 'Erp::Menu:ConfigPackages',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-box-open',
    order: 10,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart',
  },
  {
    path: '/erp/rapid-start/templates',
    name: 'Erp::Menu:ConfigTemplates',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-clone',
    order: 11,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart',
  },
  {
    path: '/erp/rapid-start/import',
    name: 'Erp::Menu:ImportData',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-file-import',
    order: 12,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart.Apply',
  },
];

export const APP_ROUTE_PROVIDER = [
  { provide: APP_INITIALIZER, useFactory: configureRoutes, deps: [RoutesService], multi: true },
  // The top bar's right-hand side: page search, the menu suite, then the company, ahead of
  // language and user.
  provideAppInitializer(() => {
    inject(NavItemsService).addItems([
      { id: 'Erp.PageSearch', order: 1, component: PageSearchComponent },
      { id: 'Erp.MenuSuite', order: 2, component: MenuSuiteButtonComponent },
      { id: 'Erp.Company', order: 3, component: CompanyMenuComponent },
    ]);
  }),
];

function configureRoutes(routesService: RoutesService) {
  return () => {
    routesService.add(ERP_ROUTES);
  };
}
