import { ABP, RoutesService, eLayoutType } from '@abp/ng.core';
import { NavItemsService } from '@abp/ng.theme.shared';
import { APP_INITIALIZER, inject, provideAppInitializer } from '@angular/core';
import { CompanyMenuComponent } from './erp/components/company-menu/company-menu.component';
import { MenuSuiteButtonComponent } from './erp/components/menu-suite/menu-suite-button.component';
import { PageSearchComponent } from './erp/components/menu-suite/page-search.component';

/**
 * The module each ERP menu entry belongs to. Entries of a module this company has switched off are
 * left out of the menu; see `ErpModuleRoutesService`. Anything not named here belongs to the core
 * and is always shown.
 */
export const ERP_ROUTE_MODULE: Record<string, string> = {
  'Erp::Menu:ChartOfAccounts': 'Finance',
  'Erp::Menu:Journals': 'Finance',
  'Erp::Menu:SalesInvoices': 'Sales',
  'Erp::Menu:PurchaseInvoices': 'Purchasing',
  'Erp::Menu:Reports': 'Reporting',
  'Erp::Menu:RequestsToApprove': 'Approvals',
  'Erp::Menu:Workflows': 'Approvals',
  'Erp::Menu:ApprovalUserSetup': 'Approvals',
  'Erp::Menu:WebServices': 'Integration',
  'Erp::Menu:Webhooks': 'Integration',
  'Erp::Menu:JobQueue': 'Core',
  'Erp::Menu:DataExport': 'DataExport',
  'Erp::Menu:Customers': 'Sales',
  'Erp::Menu:Vendors': 'Purchasing',
  'Erp::Menu:Items': 'Inventory',
  'Erp::Menu:UnitsOfMeasure': 'Inventory',
  'Erp::Menu:ItemCategories': 'Inventory',
  'Erp::Menu:GeneralLedgerSetup': 'Finance',
  'Erp::Menu:GenBusPostingGroups': 'Finance',
  'Erp::Menu:GenProdPostingGroups': 'Finance',
  'Erp::Menu:GeneralPostingSetup': 'Finance',
  'Erp::Menu:CustomerPostingGroups': 'Sales',
  'Erp::Menu:VendorPostingGroups': 'Purchasing',
  'Erp::Menu:InventoryPostingGroups': 'Inventory',
  'Erp::Menu:InventoryPostingSetup': 'Inventory',
  'Erp::Menu:VatBusPostingGroups': 'Finance',
  'Erp::Menu:VatProdPostingGroups': 'Finance',
  'Erp::Menu:VatPostingSetup': 'Finance',
  'Erp::Menu:PaymentTerms': 'Finance',
  'Erp::Menu:Currencies': 'Finance',
  'Erp::Menu:CurrencyExchangeRates': 'Finance',
  'Erp::Menu:AccountingPeriods': 'Finance',
  'Erp::Menu:VatEntries': 'Finance',
  'Erp::Menu:PaymentMethods': 'Finance',
  'Erp::Menu:CashManagement': 'CashManagement',
  'Erp::Menu:BankAccounts': 'CashManagement',
  'Erp::Menu:BankAccountLedgerEntries': 'CashManagement',
  'Erp::Menu:BankAccountPostingGroups': 'CashManagement',
  'Erp::Menu:Locations': 'Inventory',
  'Erp::Menu:InventorySetup': 'Inventory',
  'Erp::Menu:SalespeoplePurchasers': 'Sales',
  'Erp::Menu:HumanResources': 'HumanResources',
  'Erp::Menu:Employees': 'HumanResources',
  'Erp::Menu:EmployeeAbsences': 'HumanResources',
  'Erp::Menu:CausesOfAbsence': 'HumanResources',
  'Erp::Menu:Qualifications': 'HumanResources',
  'Erp::Menu:Unions': 'HumanResources',
  'Erp::Menu:EmploymentContracts': 'HumanResources',
  'Erp::Menu:PeriodicActivities': 'Finance',
  'Erp::Menu:VatStatement': 'Finance',
  'Erp::Menu:VatSettlement': 'Finance',
  'Erp::Menu:AdjustExchangeRates': 'Finance',
  'Erp::Menu:CustomerLedgerEntries': 'Sales',
  'Erp::Menu:VendorLedgerEntries': 'Purchasing',
  'Erp::Menu:EmployeeLedgerEntries': 'HumanResources',
  'Erp::Menu:GroundsForTermination': 'HumanResources',
  'Erp::Menu:HumanResourceUnitsOfMeasure': 'HumanResources',
  'Erp::Menu:EmployeePostingGroups': 'HumanResources',
  'Erp::Menu:HumanResourcesSetup': 'HumanResources',
  'Erp::Menu:ConfigWorksheet': 'RapidStart',
  'Erp::Menu:ConfigPackages': 'RapidStart',
  'Erp::Menu:ConfigTemplates': 'RapidStart',
  'Erp::Menu:ImportData': 'RapidStart',
  'Erp::Menu:FixedAssetManagement': 'FixedAssets',
  'Erp::Menu:Budgets': 'Finance',
  'Erp::Menu:SourceCodes': 'Finance',
  'Erp::Menu:ReasonCodes': 'Finance',
  'Erp::Menu:CountriesRegions': 'Finance',
  'Erp::Menu:PostCodes': 'Finance',
  'Erp::Menu:ShipmentMethods': 'Finance',
  'Erp::Menu:ResponsibilityCenters': 'Finance',
  'Erp::Menu:UserSetups': 'Finance',
  'Erp::Menu:GLBudgetNames': 'Finance',
  'Erp::Menu:GLBudgetEntries': 'Finance',
  'Erp::Menu:CustomerBankAccounts': 'Sales',
  'Erp::Menu:VendorBankAccounts': 'Purchasing',
  'Erp::Menu:OrderAddresses': 'Purchasing',
  'Erp::Menu:ItemVendors': 'Purchasing',
  'Erp::Menu:BankAccReconciliations': 'CashManagement',
  'Erp::Menu:BankAccountStatements': 'CashManagement',
  'Erp::Menu:CheckLedgerEntries': 'CashManagement',
  'Erp::Menu:Relatives': 'HumanResources',
  'Erp::Menu:MiscArticles': 'HumanResources',
  'Erp::Menu:Confidentials': 'HumanResources',
  'Erp::Menu:EmployeeStatisticsGroups': 'HumanResources',
  'Erp::Menu:EmployeeRelatives': 'HumanResources',
  'Erp::Menu:EmployeeQualifications': 'HumanResources',
  'Erp::Menu:MiscArticleInformations': 'HumanResources',
  'Erp::Menu:ConfidentialInformations': 'HumanResources',
  'Erp::Menu:AlternativeAddresses': 'HumanResources',
  'Erp::Menu:FAClasses': 'FixedAssets',
  'Erp::Menu:FASubclasses': 'FixedAssets',
  'Erp::Menu:FALocations': 'FixedAssets',
  'Erp::Menu:Maintenances': 'FixedAssets',
  'Erp::Menu:DepreciationBooks': 'FixedAssets',
  'Erp::Menu:FAPostingGroups': 'FixedAssets',
  'Erp::Menu:FASetups': 'FixedAssets',
  'Erp::Menu:FixedAssets': 'FixedAssets',
  'Erp::Menu:FADepreciationBooks': 'FixedAssets',
  'Erp::Menu:FALedgerEntries': 'FixedAssets',
  'Erp::Menu:MaintenanceRegistrations': 'FixedAssets',
  'Erp::Menu:MainAssetComponents': 'FixedAssets',
  'Erp::Menu:ReportSelections': 'Reporting',
  'Erp::Menu:CustomReportSelections': 'Reporting',
  'Erp::Menu:WorkflowUserGroups': 'Approvals',
  'Erp::Menu:WorkflowUserGroupMembers': 'Approvals',
  'Erp::Menu:StandardReports': 'Reporting',
  'Erp::Menu:Pensions': 'Pensions',
  'Erp::Menu:PensionSetup': 'Pensions',
  'Erp::Menu:PensionSchemes': 'Pensions',
  'Erp::Menu:PensionSponsors': 'Pensions',
  'Erp::Menu:PensionMembers': 'Pensions',
  'Erp::Menu:PensionContributions': 'Pensions',
  'Erp::Menu:MemberExits': 'Pensions',
  'Erp::Menu:MemberLedgerEntries': 'Pensions',
  'Erp::Menu:PensionInterestRates': 'Pensions',
  'Erp::Menu:ExitReasons': 'Pensions',
  'Erp::Menu:LumpsumTaxTables': 'Pensions',
  'Erp::Menu:LumpsumTaxBands': 'Pensions',
  'Erp::Menu:Academics': 'Academics',
  'Erp::Menu:AcademicConfiguration': 'Academics',
  'Erp::Menu:StudentApplications': 'Academics',
  'Erp::Menu:Students': 'Academics',
  'Erp::Menu:SemesterRegistrations': 'Academics',
  'Erp::Menu:StudentUnits': 'Academics',
  'Erp::Menu:StudentBills': 'Academics',
  'Erp::Menu:ExamResults': 'Academics',
  'Erp::Menu:Programmes': 'Academics',
  'Erp::Menu:ProgrammeStages': 'Academics',
  'Erp::Menu:CourseUnits': 'Academics',
  'Erp::Menu:AcademicYears': 'Academics',
  'Erp::Menu:Semesters': 'Academics',
  'Erp::Menu:Intakes': 'Academics',
  'Erp::Menu:ExamCategories': 'Academics',
  'Erp::Menu:GradingBands': 'Academics',
  'Erp::Menu:ExamComponents': 'Academics',
  'Erp::Menu:FeeItems': 'Academics',
  'Erp::Menu:FeeStructure': 'Academics',
  'Erp::Menu:AcademicSetup': 'Academics',
  'Erp::Menu:StudentReceipts': 'Academics',
  'Erp::Menu:StudentRefunds': 'Academics',
  'Erp::Menu:StudentStatusChanges': 'Academics',
  'Erp::Menu:Pensioners': 'Pensions',
  'Erp::Menu:PensionPayrolls': 'Pensions',
  'Erp::Menu:PensionBenefitCalculations': 'Pensions',
  'Erp::Menu:PensionBeneficiaries': 'Pensions',
  'Erp::Menu:MemberStatusEntries': 'Pensions',
  'Erp::Menu:MemberSalaryEntries': 'Pensions',
  'Erp::Menu:PensionContributionRates': 'Pensions',
  'Erp::Menu:PensionVestingScales': 'Pensions',
  'Erp::Menu:PensionIncrements': 'Pensions',
  'Erp::Menu:PensionerChangeEntries': 'Pensions',
  'Erp::Menu:PensionTaxReliefLimits': 'Pensions',
  'Erp::Menu:PensionBanks': 'Pensions',
  'Erp::Menu:PensionBankBranches': 'Pensions',
  'Erp::Menu:PensionerPayModes': 'Pensions',
  'Erp::Menu:PensionerPayItems': 'Pensions',
  'Erp::Menu:PensionerSuspensionReasons': 'Pensions',
  'Erp::Menu:PensionRevisionReasons': 'Pensions',
  'Erp::Menu:OtherPensionSchemes': 'Pensions',
  'Erp::Menu:ExitReasonDocuments': 'Pensions',
  'Erp::Menu:PensionAgeFactors': 'Pensions',
  'Erp::Menu:PensionerPayItemAssignments': 'Pensions',
  'Erp::Menu:MemberExitDocuments': 'Pensions',
  'Erp::Menu:CampusServices': 'Academics',
  'Erp::Menu:Timetable': 'Academics',
  'Erp::Menu:AttendanceRegisters': 'Academics',
  'Erp::Menu:HostelAllocations': 'Academics',
  'Erp::Menu:ClinicVisits': 'Academics',
  'Erp::Menu:LaundryOrders': 'Academics',
  'Erp::Menu:ShortCourseApplications': 'Academics',
  'Erp::Menu:LectureRooms': 'Academics',
  'Erp::Menu:Hostels': 'Academics',
  'Erp::Menu:HostelRooms': 'Academics',
  'Erp::Menu:LaundryItems': 'Academics',
  'Erp::Menu:ShortCourses': 'Academics',
  'Erp::Menu:Payroll': 'Payroll',
  'Erp::Menu:PayrollRuns': 'Payroll',
  'Erp::Menu:Payslips': 'Payroll',
  'Erp::Menu:EmployeePayItems': 'Payroll',
  'Erp::Menu:PayrollReports': 'Payroll',
  'Erp::Menu:PayrollEarnings': 'Payroll',
  'Erp::Menu:PayrollDeductions': 'Payroll',
  'Erp::Menu:PayrollTaxBands': 'Payroll',
  'Erp::Menu:PayrollSetup': 'Payroll',
  'Erp::Menu:PaymentVouchers': 'CashManagement',
  'Erp::Menu:PaymentTypes': 'CashManagement',
  'Erp::Menu:PaymentDeductionCodes': 'CashManagement',
  'Erp::Menu:CashManagementSetup': 'CashManagement',
};

/** The ERP menu, defined once so it can be rebuilt when a module is switched on or off. */
export const ERP_ROUTES: ABP.Route[] = [
  {
    path: '/',
    name: 'Erp::Menu:Home',
    iconClass: 'fas fa-home',
    order: 1,
    layout: eLayoutType.application,
  },
  {
    path: '/erp',
    name: 'Erp::Menu:Erp',
    iconClass: 'fas fa-calculator',
    order: 2,
    layout: eLayoutType.application,
  },
  {
    path: '/erp/chart-of-accounts',
    name: 'Erp::Menu:ChartOfAccounts',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-list-ol',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.GLAccounts',
  },
  {
    path: '/erp/sales-invoices',
    name: 'Erp::Menu:SalesInvoices',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-file-invoice-dollar',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.SalesDocuments',
  },
  {
    path: '/erp/purchase-invoices',
    name: 'Erp::Menu:PurchaseInvoices',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-shopping-cart',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PurchaseDocuments',
  },
  {
    // A group only: the tables every document and journal line looks records up in.
    name: 'Erp::Menu:MasterData',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-database',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy:
      'Erp.Customers || Erp.Vendors || Erp.Items || Erp.UnitsOfMeasure || Erp.ItemCategories || Erp.Locations || Erp.SalespeoplePurchasers',
  },
  {
    path: '/erp/customers',
    name: 'Erp::Menu:Customers',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-user-tie',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Customers',
  },
  {
    path: '/erp/vendors',
    name: 'Erp::Menu:Vendors',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-truck-field',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Vendors',
  },
  {
    path: '/erp/finance/customer-ledger-entries',
    name: 'Erp::Menu:CustomerLedgerEntries',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-file-invoice',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Customers',
  },
  {
    path: '/erp/finance/vendor-ledger-entries',
    name: 'Erp::Menu:VendorLedgerEntries',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-file-invoice',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Vendors',
  },
  {
    path: '/erp/items',
    name: 'Erp::Menu:Items',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-box',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Items',
  },
  {
    path: '/erp/units-of-measure',
    name: 'Erp::Menu:UnitsOfMeasure',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-ruler-combined',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.UnitsOfMeasure',
  },
  {
    path: '/erp/item-categories',
    name: 'Erp::Menu:ItemCategories',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-sitemap',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ItemCategories',
  },
  {
    path: '/erp/locations',
    name: 'Erp::Menu:Locations',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-warehouse',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Locations',
  },
  {
    path: '/erp/salespeople-purchasers',
    name: 'Erp::Menu:SalespeoplePurchasers',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-user-tag',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.SalespeoplePurchasers',
  },
  {
    // A group only: the posting groups master data carries and the setups that turn them into
    // G/L accounts.
    name: 'Erp::Menu:PostingSetup',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-diagram-project',
    order: 85,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/general-posting-setup',
    name: 'Erp::Menu:GeneralPostingSetup',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-table-cells',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/gen-bus-posting-groups',
    name: 'Erp::Menu:GenBusPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-people-group',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/gen-prod-posting-groups',
    name: 'Erp::Menu:GenProdPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-tags',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/customer-posting-groups',
    name: 'Erp::Menu:CustomerPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-user-tag',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vendor-posting-groups',
    name: 'Erp::Menu:VendorPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-truck-ramp-box',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/inventory-posting-groups',
    name: 'Erp::Menu:InventoryPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-warehouse',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/inventory-posting-setup',
    name: 'Erp::Menu:InventoryPostingSetup',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-boxes-stacked',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vat-posting-setup',
    name: 'Erp::Menu:VatPostingSetup',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-receipt',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vat-bus-posting-groups',
    name: 'Erp::Menu:VatBusPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-user-shield',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    path: '/erp/vat-prod-posting-groups',
    name: 'Erp::Menu:VatProdPostingGroups',
    parentName: 'Erp::Menu:PostingSetup',
    iconClass: 'fas fa-percent',
    order: 10,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    // A group only: the finance code tables and the VAT ledger.
    name: 'Erp::Menu:FinanceSetup',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-scale-balanced',
    order: 84,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup || Erp.VatEntries',
  },
  {
    path: '/erp/payment-terms',
    name: 'Erp::Menu:PaymentTerms',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-calendar-day',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/currencies',
    name: 'Erp::Menu:Currencies',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-money-bill-wave',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/currency-exchange-rates',
    name: 'Erp::Menu:CurrencyExchangeRates',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-right-left',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/finance/accounting-periods',
    name: 'Erp::Menu:AccountingPeriods',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-calendar-alt',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/payment-methods',
    name: 'Erp::Menu:PaymentMethods',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-credit-card',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/finance/vat-entries',
    name: 'Erp::Menu:VatEntries',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-receipt',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.VatEntries',
  },
  {
    // A group only: the period-end jobs.
    name: 'Erp::Menu:PeriodicActivities',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-calendar-check',
    order: 85,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PeriodicActivities || Erp.VatEntries',
  },
  {
    path: '/erp/finance/vat-return',
    name: 'Erp::Menu:VatStatement',
    parentName: 'Erp::Menu:PeriodicActivities',
    iconClass: 'fas fa-file-invoice-dollar',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.VatEntries',
  },
  {
    path: '/erp/finance/vat-settlement',
    name: 'Erp::Menu:VatSettlement',
    parentName: 'Erp::Menu:PeriodicActivities',
    iconClass: 'fas fa-scale-balanced',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PeriodicActivities.SettleVat',
  },
  {
    path: '/erp/finance/exch-rate-adjustment',
    name: 'Erp::Menu:AdjustExchangeRates',
    parentName: 'Erp::Menu:PeriodicActivities',
    iconClass: 'fas fa-right-left',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PeriodicActivities',
  },
  {
    // A group only: bank accounts and their setup.
    name: 'Erp::Menu:CashManagement',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-building-columns',
    order: 86,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankAccounts || Erp.PostingSetup',
  },
  {
    path: '/erp/bank-accounts',
    name: 'Erp::Menu:BankAccounts',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-building-columns',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankAccounts',
  },
  {
    path: '/erp/finance/bank-ledger-entries',
    name: 'Erp::Menu:BankAccountLedgerEntries',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-list-ul',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankAccounts',
  },
  {
    path: '/erp/bank-account-posting-groups',
    name: 'Erp::Menu:BankAccountPostingGroups',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-vault',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PostingSetup',
  },
  {
    // A group only: employees, absences and the HR code tables.
    name: 'Erp::Menu:HumanResources',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-id-badge',
    order: 87,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees || Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employees',
    name: 'Erp::Menu:Employees',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-id-badge',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/finance/employee-ledger-entries',
    name: 'Erp::Menu:EmployeeLedgerEntries',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-receipt',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/employee-absences',
    name: 'Erp::Menu:EmployeeAbsences',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-umbrella-beach',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/causes-of-absence',
    name: 'Erp::Menu:CausesOfAbsence',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-notes-medical',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/qualifications',
    name: 'Erp::Menu:Qualifications',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-graduation-cap',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employment-contracts',
    name: 'Erp::Menu:EmploymentContracts',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-file-signature',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/unions',
    name: 'Erp::Menu:Unions',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-handshake',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/grounds-for-termination',
    name: 'Erp::Menu:GroundsForTermination',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-door-open',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/hr-units-of-measure',
    name: 'Erp::Menu:HumanResourceUnitsOfMeasure',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-hourglass-half',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employee-posting-groups',
    name: 'Erp::Menu:EmployeePostingGroups',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-people-arrows',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    // A group only: it has no page of its own.
    name: 'Erp::Menu:Journals',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-book',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Journals || Erp.GLRegisters',
  },
  {
    path: '/erp/finance/general-journal',
    name: 'Erp::Menu:GeneralJournal',
    parentName: 'Erp::Menu:Journals',
    iconClass: 'fas fa-pen-to-square',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Journals',
  },
  {
    path: '/erp/finance/journal-templates',
    name: 'Erp::Menu:JournalTemplates',
    parentName: 'Erp::Menu:Journals',
    iconClass: 'fas fa-layer-group',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Journals',
  },
  {
    path: '/erp/finance/registers',
    name: 'Erp::Menu:GLRegisters',
    parentName: 'Erp::Menu:Journals',
    iconClass: 'fas fa-clock-rotate-left',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.GLRegisters',
  },
  {
    name: 'Erp::Menu:Reports',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-chart-line',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Reports || Erp.AccountSchedules',
  },
  {
    path: '/erp/reports/financial',
    name: 'Erp::Menu:FinancialReports',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-file-invoice',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Reports',
  },
  {
    path: '/erp/reports/account-schedules',
    name: 'Erp::Menu:AccountSchedules',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-table',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.AccountSchedules',
  },
  {
    path: '/erp/reports/column-layouts',
    name: 'Erp::Menu:ColumnLayouts',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-table-columns',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.AccountSchedules',
  },
  {
    path: '/erp/reports/report-layouts',
    name: 'Erp::Menu:ReportLayouts',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-file-invoice',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ReportLayouts',
  },
  {
    path: '/erp/approvals',
    name: 'Erp::Menu:RequestsToApprove',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-clipboard-check',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Workflows',
  },
  {
    // A group only: it has no page of its own.
    name: 'Erp::Menu:Setup',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-cog',
    order: 90,
    layout: eLayoutType.application,
    requiredPolicy:
      'Erp.Modules || Erp.Theme || Erp.Profiles || Erp.GeneralLedgerSetup || Erp.InventorySetup || Erp.HumanResourcesSetup || Erp.NoSeries || Erp.SalesSetup || Erp.PurchaseSetup || Erp.Workflows || Erp.ApprovalUserSetup || Erp.WebServices || Erp.Webhooks || Erp.DataExport || Erp.RapidStart',
  },
  {
    path: '/erp/setup/modules',
    name: 'Erp::Menu:Modules',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-sliders',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Modules',
  },
  {
    path: '/erp/setup/theme',
    name: 'Erp::Menu:Theme',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-palette',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Theme',
  },
  {
    path: '/erp/setup/profiles',
    name: 'Erp::Menu:Profiles',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-users-gear',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Profiles',
  },
  {
    path: '/erp/setup/general-ledger',
    name: 'Erp::Menu:GeneralLedgerSetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-book',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.GeneralLedgerSetup',
  },
  {
    path: '/erp/setup/inventory',
    name: 'Erp::Menu:InventorySetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-boxes-stacked',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.InventorySetup',
  },
  {
    path: '/erp/setup/human-resources',
    name: 'Erp::Menu:HumanResourcesSetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-id-card',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/setup/no-series',
    name: 'Erp::Menu:NoSeries',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-list-ol',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.NoSeries',
  },
  {
    path: '/erp/setup/document-numbering',
    name: 'Erp::DocumentNumbering',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-hashtag',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.NoSeries && (Erp.SalesSetup || Erp.PurchaseSetup)',
  },
  {
    path: '/erp/setup/workflows',
    name: 'Erp::Menu:Workflows',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-project-diagram',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Workflows.Manage',
  },
  {
    path: '/erp/setup/approval-users',
    name: 'Erp::Menu:ApprovalUserSetup',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-user-check',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ApprovalUserSetup',
  },
  {
    path: '/erp/setup/web-services',
    name: 'Erp::Menu:WebServices',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-plug',
    order: 6,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.WebServices && Erp.DataExport',
  },
  {
    path: '/erp/setup/webhooks',
    name: 'Erp::Menu:Webhooks',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-satellite-dish',
    order: 7,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Webhooks && Erp.DataExport',
  },
  {
    path: '/erp/setup/data-export',
    name: 'Erp::Menu:DataExport',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-file-export',
    order: 8,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.DataExport',
  },
  {
    path: '/erp/setup/job-queue',
    name: 'Erp::Menu:JobQueue',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-tasks',
    order: 8.5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.JobQueue',
  },
  {
    path: '/erp/rapid-start/worksheet',
    name: 'Erp::Menu:ConfigWorksheet',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-list-check',
    order: 9,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart',
  },
  {
    path: '/erp/rapid-start/packages',
    name: 'Erp::Menu:ConfigPackages',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-box-open',
    order: 10,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart',
  },
  {
    path: '/erp/rapid-start/templates',
    name: 'Erp::Menu:ConfigTemplates',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-clone',
    order: 11,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart',
  },
  {
    path: '/erp/rapid-start/import',
    name: 'Erp::Menu:ImportData',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-file-import',
    order: 12,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.RapidStart.Apply',
  },
  {
    name: 'Erp::Menu:FixedAssetManagement',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-building',
    order: 88,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssets || Erp.FixedAssetSetup',
  },
  {
    name: 'Erp::Menu:Budgets',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-sack-dollar',
    order: 85.5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Budgets',
  },
  {
    path: '/erp/source-codes',
    name: 'Erp::Menu:SourceCodes',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-tag',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/reason-codes',
    name: 'Erp::Menu:ReasonCodes',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-circle-question',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/countries-regions',
    name: 'Erp::Menu:CountriesRegions',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-globe',
    order: 23,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/post-codes',
    name: 'Erp::Menu:PostCodes',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-envelopes-bulk',
    order: 24,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/shipment-methods',
    name: 'Erp::Menu:ShipmentMethods',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-truck-fast',
    order: 25,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/responsibility-centers',
    name: 'Erp::Menu:ResponsibilityCenters',
    parentName: 'Erp::Menu:FinanceSetup',
    iconClass: 'fas fa-sitemap',
    order: 26,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FinanceSetup',
  },
  {
    path: '/erp/user-setups',
    name: 'Erp::Menu:UserSetups',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-user-gear',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.UserSetup',
  },
  {
    path: '/erp/gl-budget-names',
    name: 'Erp::Menu:GLBudgetNames',
    parentName: 'Erp::Menu:Budgets',
    iconClass: 'fas fa-sack-dollar',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Budgets',
  },
  {
    path: '/erp/gl-budget-entries',
    name: 'Erp::Menu:GLBudgetEntries',
    parentName: 'Erp::Menu:Budgets',
    iconClass: 'fas fa-coins',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Budgets',
  },
  {
    path: '/erp/customer-bank-accounts',
    name: 'Erp::Menu:CustomerBankAccounts',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-building-columns',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Customers',
  },
  {
    path: '/erp/vendor-bank-accounts',
    name: 'Erp::Menu:VendorBankAccounts',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-building-columns',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Vendors',
  },
  {
    path: '/erp/order-addresses',
    name: 'Erp::Menu:OrderAddresses',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-location-dot',
    order: 23,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Vendors',
  },
  {
    path: '/erp/item-vendors',
    name: 'Erp::Menu:ItemVendors',
    parentName: 'Erp::Menu:MasterData',
    iconClass: 'fas fa-boxes-packing',
    order: 24,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Vendors',
  },
  {
    path: '/erp/bank-acc-reconciliations',
    name: 'Erp::Menu:BankAccReconciliations',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-scale-balanced',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankReconciliations',
  },
  {
    path: '/erp/bank-account-statements',
    name: 'Erp::Menu:BankAccountStatements',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-file-invoice',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankReconciliations',
  },
  {
    path: '/erp/check-ledger-entries',
    name: 'Erp::Menu:CheckLedgerEntries',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-money-check',
    order: 23,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.BankAccounts',
  },
  {
    path: '/erp/relatives',
    name: 'Erp::Menu:Relatives',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-people-roof',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/misc-articles',
    name: 'Erp::Menu:MiscArticles',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-key',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/confidentials',
    name: 'Erp::Menu:Confidentials',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-user-secret',
    order: 23,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employee-statistics-groups',
    name: 'Erp::Menu:EmployeeStatisticsGroups',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-chart-pie',
    order: 24,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.HumanResourcesSetup',
  },
  {
    path: '/erp/employee-relatives',
    name: 'Erp::Menu:EmployeeRelatives',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-people-roof',
    order: 25,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/employee-qualifications',
    name: 'Erp::Menu:EmployeeQualifications',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-graduation-cap',
    order: 26,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/misc-article-informations',
    name: 'Erp::Menu:MiscArticleInformations',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-key',
    order: 27,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/confidential-informations',
    name: 'Erp::Menu:ConfidentialInformations',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-user-secret',
    order: 28,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/alternative-addresses',
    name: 'Erp::Menu:AlternativeAddresses',
    parentName: 'Erp::Menu:HumanResources',
    iconClass: 'fas fa-location-dot',
    order: 29,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Employees',
  },
  {
    path: '/erp/fa-classes',
    name: 'Erp::Menu:FAClasses',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-layer-group',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssetSetup',
  },
  {
    path: '/erp/fa-subclasses',
    name: 'Erp::Menu:FASubclasses',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-layer-group',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssetSetup',
  },
  {
    path: '/erp/fa-locations',
    name: 'Erp::Menu:FALocations',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-map-pin',
    order: 23,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssetSetup',
  },
  {
    path: '/erp/maintenances',
    name: 'Erp::Menu:Maintenances',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-screwdriver-wrench',
    order: 24,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssetSetup',
  },
  {
    path: '/erp/depreciation-books',
    name: 'Erp::Menu:DepreciationBooks',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-book',
    order: 25,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssetSetup',
  },
  {
    path: '/erp/fa-posting-groups',
    name: 'Erp::Menu:FAPostingGroups',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-diagram-project',
    order: 26,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssetSetup',
  },
  {
    path: '/erp/setup/fa-setups',
    name: 'Erp::Menu:FASetups',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-gears',
    order: 27,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssetSetup',
  },
  {
    path: '/erp/fixed-assets',
    name: 'Erp::Menu:FixedAssets',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-building',
    order: 28,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssets',
  },
  {
    path: '/erp/fa-depreciation-books',
    name: 'Erp::Menu:FADepreciationBooks',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-book-open',
    order: 29,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssets',
  },
  {
    path: '/erp/fa-ledger-entries',
    name: 'Erp::Menu:FALedgerEntries',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-receipt',
    order: 30,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssets',
  },
  {
    path: '/erp/maintenance-registrations',
    name: 'Erp::Menu:MaintenanceRegistrations',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-screwdriver-wrench',
    order: 31,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssets',
  },
  {
    path: '/erp/main-asset-components',
    name: 'Erp::Menu:MainAssetComponents',
    parentName: 'Erp::Menu:FixedAssetManagement',
    iconClass: 'fas fa-cubes',
    order: 32,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.FixedAssets',
  },
  {
    path: '/erp/report-selections',
    name: 'Erp::Menu:ReportSelections',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-print',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ReportSelections',
  },
  {
    path: '/erp/custom-report-selections',
    name: 'Erp::Menu:CustomReportSelections',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-envelope-open-text',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.ReportSelections',
  },
  {
    path: '/erp/workflow-user-groups',
    name: 'Erp::Menu:WorkflowUserGroups',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-users-gear',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.WorkflowUserGroups',
  },
  {
    path: '/erp/workflow-user-group-members',
    name: 'Erp::Menu:WorkflowUserGroupMembers',
    parentName: 'Erp::Menu:Setup',
    iconClass: 'fas fa-user-group',
    order: 23,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.WorkflowUserGroups',
  },
  {
    path: '/erp/reports/standard',
    name: 'Erp::Menu:StandardReports',
    parentName: 'Erp::Menu:Reports',
    iconClass: 'fas fa-rectangle-list',
    order: 1.5,
    layout: eLayoutType.application,
  },
  {
    // A group only: schemes, sponsors, members, contributions, interest and exits.
    name: 'Erp::Menu:Pensions',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-piggy-bank',
    order: 89,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Pensions || Erp.PensionSetup',
  },
  {
    path: '/erp/pension-schemes',
    name: 'Erp::Menu:PensionSchemes',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-landmark',
    order: 20,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PensionSetup',
  },
  {
    path: '/erp/pension-sponsors',
    name: 'Erp::Menu:PensionSponsors',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-building-user',
    order: 1,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Pensions',
  },
  {
    path: '/erp/pension-members',
    name: 'Erp::Menu:PensionMembers',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-user-shield',
    order: 2,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Pensions',
  },
  {
    path: '/erp/pension-contributions',
    name: 'Erp::Menu:PensionContributions',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-file-invoice-dollar',
    order: 3,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Pensions',
  },
  {
    path: '/erp/member-exits',
    name: 'Erp::Menu:MemberExits',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-door-open',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Pensions',
  },
  {
    path: '/erp/member-ledger-entries',
    name: 'Erp::Menu:MemberLedgerEntries',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-receipt',
    order: 5,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Pensions',
  },
  {
    path: '/erp/pension-interest-rates',
    name: 'Erp::Menu:PensionInterestRates',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-chart-line',
    order: 21,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PensionSetup',
  },
  {
    path: '/erp/exit-reasons',
    name: 'Erp::Menu:ExitReasons',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-door-closed',
    order: 22,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PensionSetup',
  },
  {
    path: '/erp/lumpsum-tax-tables',
    name: 'Erp::Menu:LumpsumTaxTables',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-percent',
    order: 23,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PensionSetup',
  },
  {
    path: '/erp/lumpsum-tax-bands',
    name: 'Erp::Menu:LumpsumTaxBands',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-layer-group',
    order: 24,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PensionSetup',
  },
  {
    path: '/erp/setup/pension-setup',
    name: 'Erp::Menu:PensionSetup',
    parentName: 'Erp::Menu:Pensions',
    iconClass: 'fas fa-gears',
    order: 40,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PensionSetup',
  },
  {
    // A group only: admissions, students, registration, billing and exam results.
    name: 'Erp::Menu:Academics',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-graduation-cap',
    order: 90,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Academics || Erp.AcademicSetup',
  },
  ...academicMenu('Erp::Menu:Academics', 'Erp.Academics', [
    ['/erp/student-applications', 'StudentApplications', 'fas fa-file-signature'],
    ['/erp/students', 'Students', 'fas fa-user-graduate'],
    ['/erp/semester-registrations', 'SemesterRegistrations', 'fas fa-clipboard-list'],
    ['/erp/student-units', 'StudentUnits', 'fas fa-book-open'],
    ['/erp/student-bills', 'StudentBills', 'fas fa-file-invoice-dollar'],
    ['/erp/student-receipts', 'StudentReceipts', 'fas fa-receipt'],
    ['/erp/student-refunds', 'StudentRefunds', 'fas fa-hand-holding-dollar'],
    ['/erp/exam-results', 'ExamResults', 'fas fa-square-poll-vertical'],
    ['/erp/student-status-changes', 'StudentStatusChanges', 'fas fa-user-clock'],
  ]),
  ...academicMenu('Erp::Menu:Pensions', 'Erp.Pensions', [
    ['/erp/pensioners', 'Pensioners', 'fas fa-person-cane'],
    ['/erp/pension-payrolls', 'PensionPayrolls', 'fas fa-money-bill-wave'],
    ['/erp/pension-benefit-calculations', 'PensionBenefitCalculations', 'fas fa-calculator'],
    ['/erp/pension-increments', 'PensionIncrements', 'fas fa-arrow-trend-up'],
    ['/erp/pensioner-change-entries', 'PensionerChangeEntries', 'fas fa-clock-rotate-left'],
    ['/erp/pension-beneficiaries', 'PensionBeneficiaries', 'fas fa-people-roof'],
    ['/erp/member-status-entries', 'MemberStatusEntries', 'fas fa-timeline'],
    ['/erp/member-salary-entries', 'MemberSalaryEntries', 'fas fa-money-check'],
    ['/erp/pension-contribution-rates', 'PensionContributionRates', 'fas fa-percent'],
    ['/erp/pension-vesting-scales', 'PensionVestingScales', 'fas fa-stairs'],
  ]).map(route => ({ ...route, order: (route.order ?? 0) + 5 })),
  ...academicMenu('Erp::Menu:Pensions', 'Erp.PensionSetup', [['/erp/pension-tax-relief-limits', 'PensionTaxReliefLimits', 'fas fa-scale-balanced']]).map(route => ({
    ...route,
    order: 25,
  })),
  // The pension setup tables, after the tax tables and before the Pension Setup page.
  ...academicMenu('Erp::Menu:Pensions', 'Erp.PensionSetup', [
    ['/erp/pension-banks', 'PensionBanks', 'fas fa-building-columns'],
    ['/erp/pension-bank-branches', 'PensionBankBranches', 'fas fa-code-branch'],
    ['/erp/pensioner-pay-modes', 'PensionerPayModes', 'fas fa-money-bill-transfer'],
    ['/erp/pensioner-pay-items', 'PensionerPayItems', 'fas fa-list-check'],
    ['/erp/pensioner-suspension-reasons', 'PensionerSuspensionReasons', 'fas fa-circle-pause'],
    ['/erp/pension-revision-reasons', 'PensionRevisionReasons', 'fas fa-pen-ruler'],
    ['/erp/other-pension-schemes', 'OtherPensionSchemes', 'fas fa-right-left'],
    ['/erp/exit-reason-documents', 'ExitReasonDocuments', 'fas fa-file-circle-check'],
    ['/erp/pension-age-factors', 'PensionAgeFactors', 'fas fa-table-cells'],
  ]).map(route => ({ ...route, order: (route.order ?? 0) + 25 })),
  ...academicMenu('Erp::Menu:Pensions', 'Erp.Pensions', [
    ['/erp/pensioner-pay-item-assignments', 'PensionerPayItemAssignments', 'fas fa-hand-holding-dollar'],
    ['/erp/member-exit-documents', 'MemberExitDocuments', 'fas fa-folder-open'],
  ]).map(route => ({ ...route, order: (route.order ?? 0) + 15 })),
  {
    // A group only: the services around the academic records.
    name: 'Erp::Menu:CampusServices',
    parentName: 'Erp::Menu:Academics',
    iconClass: 'fas fa-school',
    order: 40,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Academics',
  },
  ...academicMenu('Erp::Menu:CampusServices', 'Erp.Academics', [
    ['/erp/timetable', 'Timetable', 'fas fa-calendar-week'],
    ['/erp/attendance-registers', 'AttendanceRegisters', 'fas fa-clipboard-user'],
    ['/erp/hostel-allocations', 'HostelAllocations', 'fas fa-key'],
    ['/erp/clinic-visits', 'ClinicVisits', 'fas fa-house-medical'],
    ['/erp/laundry-orders', 'LaundryOrders', 'fas fa-soap'],
    ['/erp/short-course-applications', 'ShortCourseApplications', 'fas fa-user-graduate'],
  ]),
  {
    // A group only: payroll runs and payslips, and what they are worked out from.
    name: 'Erp::Menu:Payroll',
    parentName: 'Erp::Menu:Erp',
    iconClass: 'fas fa-money-check-dollar',
    order: 91,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.Payroll || Erp.PayrollSetup',
  },
  ...academicMenu('Erp::Menu:Payroll', 'Erp.Payroll', [
    ['/erp/payroll-runs', 'PayrollRuns', 'fas fa-money-check-dollar'],
    ['/erp/payslips', 'Payslips', 'fas fa-file-invoice'],
    ['/erp/employee-pay-items', 'EmployeePayItems', 'fas fa-user-tag'],
    ['/erp/reports/standard', 'PayrollReports', 'fas fa-rectangle-list'],
  ]),
  ...academicMenu('Erp::Menu:Payroll', 'Erp.PayrollSetup', [
    ['/erp/payroll-earnings', 'PayrollEarnings', 'fas fa-money-bill-wave'],
    ['/erp/payroll-deductions', 'PayrollDeductions', 'fas fa-scissors'],
    ['/erp/payroll-tax-bands', 'PayrollTaxBands', 'fas fa-layer-group'],
    ['/erp/setup/payroll', 'PayrollSetup', 'fas fa-gears'],
  ]).map(route => ({ ...route, order: (route.order ?? 0) + 20 })),
  {
    path: '/erp/payment-vouchers',
    name: 'Erp::Menu:PaymentVouchers',
    parentName: 'Erp::Menu:CashManagement',
    iconClass: 'fas fa-money-check-dollar',
    order: 4,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.PaymentVouchers',
  },
  ...academicMenu('Erp::Menu:CashManagement', 'Erp.PaymentVoucherSetup', [
    ['/erp/payment-types', 'PaymentTypes', 'fas fa-money-check'],
    ['/erp/payment-deduction-codes', 'PaymentDeductionCodes', 'fas fa-scissors'],
    ['/erp/setup/cash-management', 'CashManagementSetup', 'fas fa-gears'],
  ]).map(route => ({ ...route, order: (route.order ?? 0) + 30 })),
  {
    // A group only: what is set up once and then rarely changed.
    name: 'Erp::Menu:AcademicConfiguration',
    parentName: 'Erp::Menu:Academics',
    iconClass: 'fas fa-sliders',
    order: 50,
    layout: eLayoutType.application,
    requiredPolicy: 'Erp.AcademicSetup',
  },
  ...academicMenu('Erp::Menu:AcademicConfiguration', 'Erp.AcademicSetup', [
    ['/erp/programmes', 'Programmes', 'fas fa-graduation-cap'],
    ['/erp/programme-stages', 'ProgrammeStages', 'fas fa-stairs'],
    ['/erp/course-units', 'CourseUnits', 'fas fa-book'],
    ['/erp/academic-years', 'AcademicYears', 'fas fa-calendar'],
    ['/erp/semesters', 'Semesters', 'fas fa-calendar-week'],
    ['/erp/intakes', 'Intakes', 'fas fa-user-plus'],
    ['/erp/exam-categories', 'ExamCategories', 'fas fa-award'],
    ['/erp/grading-bands', 'GradingBands', 'fas fa-ranking-star'],
    ['/erp/exam-components', 'ExamComponents', 'fas fa-chart-pie'],
    ['/erp/fee-items', 'FeeItems', 'fas fa-tags'],
    ['/erp/fee-structure', 'FeeStructure', 'fas fa-table-list'],
    ['/erp/lecture-rooms', 'LectureRooms', 'fas fa-door-open'],
    ['/erp/hostels', 'Hostels', 'fas fa-bed'],
    ['/erp/hostel-rooms', 'HostelRooms', 'fas fa-door-closed'],
    ['/erp/laundry-items', 'LaundryItems', 'fas fa-shirt'],
    ['/erp/short-courses', 'ShortCourses', 'fas fa-chalkboard'],
    ['/erp/setup/academic-setup', 'AcademicSetup', 'fas fa-gears'],
  ]),
];

/** The pages of an academic menu group, in the order given. */
function academicMenu(parentName: string, requiredPolicy: string, pages: [path: string, name: string, iconClass: string][]): ABP.Route[] {
  return pages.map(([path, name, iconClass], index) => ({
    path,
    name: `Erp::Menu:${name}`,
    parentName,
    iconClass,
    order: index + 1,
    layout: eLayoutType.application,
    requiredPolicy,
  }));
}

export const APP_ROUTE_PROVIDER = [
  { provide: APP_INITIALIZER, useFactory: configureRoutes, deps: [RoutesService], multi: true },
  // The top bar's right-hand side: page search, the menu suite, then the company, ahead of
  // language and user.
  provideAppInitializer(() => {
    inject(NavItemsService).addItems([
      { id: 'Erp.PageSearch', order: 1, component: PageSearchComponent },
      { id: 'Erp.MenuSuite', order: 2, component: MenuSuiteButtonComponent },
      { id: 'Erp.Company', order: 3, component: CompanyMenuComponent },
    ]);
  }),
];

function configureRoutes(routesService: RoutesService) {
  return () => {
    routesService.add(ERP_ROUTES);
  };
}
