<Project Sdk="Microsoft.NET.Sdk">

  

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>ABPmicroservice.SaaS</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.AutoMapper" Version="9.0.0" />
        <PackageReference Include="Volo.Abp.Ddd.Application" Version="9.0.0" />
        <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="9.0.0" />
        <ProjectReference Include="..\..\..\administration\src\ABPmicroservice.Administration.Application\ABPmicroservice.Administration.Application.csproj" />
        <ProjectReference Include="..\ABPmicroservice.SaaS.Application.Contracts\ABPmicroservice.SaaS.Application.Contracts.csproj" />
        <ProjectReference Include="..\ABPmicroservice.SaaS.Domain\ABPmicroservice.SaaS.Domain.csproj" />
    </ItemGroup>

</Project>
