<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ABPmicroservice.Administration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ABPmicroservice.Administration.Application\ABPmicroservice.Administration.Application.csproj" />
    <ProjectReference Include="..\ABPmicroservice.Administration.Domain.Tests\ABPmicroservice.Administration.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
  </ItemGroup>

</Project>
