<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ABPmicroservice.Erp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ABPmicroservice.Erp.Application\ABPmicroservice.Erp.Application.csproj" />
    <ProjectReference Include="..\ABPmicroservice.Erp.Domain.Tests\ABPmicroservice.Erp.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
  </ItemGroup>

</Project>
