<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ABPmicroservice.SaaS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.9" />
    <ProjectReference Include="..\..\src\ABPmicroservice.SaaS.EntityFrameworkCore\ABPmicroservice.SaaS.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\ABPmicroservice.SaaS.TestBase\ABPmicroservice.SaaS.TestBase.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="10.6.1" />
  </ItemGroup>

</Project>
