<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>ABPmicroservice.IdentityService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <ProjectReference Include="..\ABPmicroservice.IdentityService.EntityFrameworkCore.Tests\ABPmicroservice.IdentityService.EntityFrameworkCore.Tests.csproj" />
  </ItemGroup>

</Project>
