<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ABPmicroservice.SaaS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <ProjectReference Include="..\ABPmicroservice.SaaS.EntityFrameworkCore.Tests\ABPmicroservice.SaaS.EntityFrameworkCore.Tests.csproj" />
  </ItemGroup>

</Project>
