<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ABPmicroservice.Projects</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ABPmicroservice.Projects.Application\ABPmicroservice.Projects.Application.csproj" />
    <ProjectReference Include="..\ABPmicroservice.Projects.Domain.Tests\ABPmicroservice.Projects.Domain.Tests.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
  </ItemGroup>

</Project>
